### PR TITLE
Allow building without systemd dependency

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <teabee89@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
Why is this needed here? Isn't just ok to skip socket activation like it's currently happening (and like Docker or runc does?

**Comment by tiborvass** [comment]
@runcom it's useful for being able to build a lightweight container plugin. With the systemd dependency there is a dependency on cgo at some point which prevents me from making a static binary.

**Comment by runcom** [comment]
I see, tests are failing though

**Comment by tiborvass** [comment]
@runcom it's failing because of https://github.com/docker/docker/commit/b937aa8e6968d805527d163e6f477d496ceb88d7

**Comment by tiborvass** [comment]
@dave-tucker @runcom rebased

**Pull request merged**
