### PR TITLE
sdk: ServeTCP with tls.Config

### LINKED ISSUE #47: ServeTCP should support TLS
Docker can connect to plugins via TLS if using the JSON specification. ServeTCP should have options for TLS.

### PR DESCRIPTION
**Pull request by runcom**
Fix #47

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
failures are because we do not vendor the correct docker/docker and go get gets the latest..

**Comment by calavera** [comment]
never vendor docker/dockdr

**Comment by runcom** [comment]
ping @calavera @dave-tucker

**Comment by dave-tucker** [comment]
patch LGTM, but would rather not merge with failing CI.
agree with @calavera, we shouldn't be vendoring docker/docker

**Comment by runcom** [comment]
Fine with that, but we depend on Docker anyway now, not sure how to make CI pass :)

**Comment by dave-tucker** [comment]
I guess we need to fix the `volumes/shims` package. #49 seemed ok to me but haven't reviewed it properly nor looked at the upstream changes. The alternative would be to temporarily exclude the shims from the build

**Comment by runcom** [comment]
#49 did not work because it was wrong :( I think excluding the shim from building (as it depends on docker) would be fine @calavera wdyt

**Comment by runcom** [comment]
what do we do here?

**Comment by runcom** [comment]
ping anyone, can we merge this if it looks good?

**Comment by thaJeztah** [comment]
ping @dave-tucker @calavera PTAL

**Comment by runcom** [comment]
I'll rebase once #60 is merged which updates the golang version and tests pass

**Comment by runcom** [comment]
This is good to go now that tests pass :) (finally!)

**Comment by runcom** [comment]
all green :)

**Pull request merged**
