### PR TITLE
Add graphdriver helpers

### PR DESCRIPTION
**Pull request by samoht**
Thanks to @dave-tucker for the original version of this patch (see. #33). I've changed the interface slightly to simplify the creation of new plugins and I've added some tests, inspired from the volume helpers.

I have an other patch to add `shim.go` so we can use built-in graphdrivers as plugins, I need to write some test first (and figure how I can test that properly).

### CODE REVIEW

**Comment by icecrime** [comment]
Oooh nice!

**Comment by icecrime** [comment]
Ping @calavera @runcom @cpuguy83.

**Comment by dave-tucker** [comment]
LGTM

**Comment by runcom** [comment]
LGTM Ping @calavera

**Comment by cpuguy83** [comment]
I think we changed the graphdriver interface to include a `CreateReadWrite` for differentiating read-only and read-write layer creation.

**Comment by samoht** [comment]
I've now added the shim layer to turn upstream drivers into plugins. There are some minor issues issues with the doc and the shim, not sure where it's the best place to report/fix that. For instance:

- the doc doesn't document the `mountLabel`  argument for `Create`
- `CreateReadWrite` is not documented

**Comment by cpuguy83** [comment]
https://github.com/docker/docker/blob/master/daemon/graphdriver/driver.go#L51

**Comment by samoht** [comment]
> I think we changed the graphdriver interface to include a CreateReadWrite for differentiating read-only and read-write layer creation.

Indeed. I'll open a PR in docker/docker to add this and fix inconsistencies and add that method call to my PR.

**Comment by samoht** [comment]
Note: I still haven't tested that with a real graph driver so maybe that's not very wise to merge it immediately.

**Comment by dave-tucker** [comment]
@samoht did you manage to test with a real driver? If not, shall we merge anyway... we can always improve the code with real world testing later

**Comment by samoht** [comment]
@dave-tucker no I haven't tested it yet. But yes, feel free to merge.

**Pull request merged**
