### PR TITLE
Fix tests and add Makefile

### PR DESCRIPTION
**Pull request by dave-tucker**
- Fix network ports (my bad)
- Fix failing test since the `CapabilitiesResponse` was added
- Create Makefile for ease of running tests using Docker
  - make test = with docker
  - make test-local = using local go

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by runcom** [comment]
LGTM

**Comment by dave-tucker** [comment]
*sigh* going to see if Travis can run the tests in a container.
I'm tired to tests passing locally but failing on CI

**Comment by dave-tucker** [comment]
✅CI 
:boom:

**Comment by vdemeester** [comment]
@dave-tucker :+1:

**Comment by thaJeztah** [comment]
LGTM

**Comment by runcom** [comment]
Merging \o/

**Pull request merged**
