### PR TITLE
[WIP] Initial Commit of Graph API

### LINKED ISSUE #4: Add "graph driver" plugin example/sdk
See: https://github.com/docker/docker/blob/master/experimental/plugins_graphdriver.md

### PR DESCRIPTION
**Pull request by dave-tucker**
Fixes #4

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by dave-tucker** [comment]
/cc @cpuguy83 WDYT?

Personally, I think it'd make sense to for `Diff` and `ApplyDiff` to deal with actual tar objects as opposed to the more abstract `io.Reader`... but that's wide open for discussion.

P.S - CI will fail until I rebase when #32 is merged (my bad)

**Comment by runcom** [comment]
@dave-tucker you can rebase cause I merged #32

**Comment by dave-tucker** [comment]
@runcom :sunglasses:

**Comment by cpuguy83** [comment]
Might be nice to have an implementation that just takes a graphdriver Init function and automatically maps the resulting graphdriver to the handler functions rather than everyone writing the same code.
So instead we'd ahve something like:

```go
NewHandler(initFn graphdriver.InitFunc) *Handler
```

WDYT?

**Comment by dave-tucker** [comment]
@cpuguy83 not sure I understand your comment... typical usage would be:

```go
  d := MyGraphDriver{}
  h := graph.NewHandler(d)
  h.ServeUnix(""root", "mygraph")
```
In this case, `MyGraphDriver` is anything that implements the `Driver` interface from this package.
We're taking care of the mapping from handler -> a the `MyGraphDriver` functions

**Comment by cpuguy83** [comment]
@dave-tucker This requires someone to write basiclaly a pass-through from the graphdriver itself to the plugin helper, whereas this code should be exactly the same for everyone.
If we take a graphdriver init func as above, we can just automatically map all calls directly to the graphdriver from the plugin helper instead of requiring someone to write this shim layer.

For instance, to test this out I started writing a shim like this:

```go
type driver struct {
	vfs graphdriver.Driver
}

func (d *driver) Init(req *graph.InitRequest) error {
	fs, err := vfs.Init(req.Home, req.Opts, nil, nil)
	if err != nil {
		return err
	}
	d.vfs = graphdriver.NewNaiveDiffDriver(fs, nil, nil)
	return nil
}

func (d *driver) Create(req *graph.IDParentRequest) error {
	return d.vfs.Create(req.ID, req.Parent, "")
}

func (d *driver) Remove(req *graph.OperationRequest) error {
	return d.vfs.Remove(req.ID)
}

func (d *driver) Get(req *graph.GetRequest) (*graph.GetResponse, error) {
	dir, err := d.vfs.Get(req.ID, req.MountLabel)
	return &graph.GetResponse{Dir: dir}, err
}
```

But I think we can make it so people don't even have to write the shim.

**Comment by dave-tucker** [comment]
@cpuguy83 ah i see! you're talking about existing, in-tree graphdrivers right?

**Comment by cpuguy83** [comment]
@dave-tucker That's the example yes, but this would mean people can write a graphdriver as if they are in-tree, and not care about the plugin API layer.

**Comment by dave-tucker** [comment]
@cpuguy83 got it. will try to find some time to hack on it within the next week or so

**Comment by samoht** [comment]
I have starting working on the pass-through graph drivers (mentioning it to avoid duplicated efforts)

**Comment by samoht** [comment]
(I'll also rebase this PR)

**Comment by dave-tucker** [comment]
@samoht awesome!

**Comment by dave-tucker** [comment]
Closing in favor of #42

**Pull request closed without merging**
