### PR TITLE
Ignore empty CreatedAt

### PR DESCRIPTION
**Pull request by cblomart**
Empty CreatedAt values causes errors in docker

### CODE REVIEW

**Comment by cblomart** [comment]
Should "Status" be ignored too? 
Following docker documentation it is optional too.

**Comment by m4r10k** [comment]
Thank you for your PR! Today I wrote my first Docker volume plugin and it takes me some time to figure that out. Would be nice if this one gets merged soon! Thanks for pointing out the problem.

**Comment by dave-tucker** [comment]
@cblomart nope. that's why I'm hesitant to merge this at the moment. I should have some time to take a look properly later this week.

**Comment by dave-tucker** [comment]
In the meantime you could try running `gofmt -w -s` on the files that are misbehaving.
https://golang.org/cmd/gofmt/

**Comment by cblomart** [comment]
@dave-tucker : thanks for the advise... i bluntly gofmt all files and it goes further. I guess i now have the latest test issues (tar.Header).

**Comment by cblomart** [comment]
Ok apparently some part used by docker compress are now only in newer versions of golang so updating golang to 1.11 solved the case.
... still "go fmt" in this version didn't like one test file so i gofmted it.

Builds nowm :D

**Comment by cblomart** [comment]
@dave-tucker: looks good now... is the golang upgrade worrying?

**Comment by dave-tucker** [comment]
Nope. Thanks @cblomart.

**Pull request merged**
