### PR TITLE
sdk: support systemd socket activation

### PR DESCRIPTION
**Pull request by runcom**
we basically want plugins to be socket activated when possible, I can write some docs for docker/docker to explain more about this. So when/if a plugin dies the socket doesn't and can re-run the plugin again.

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by runcom** [comment]
ping @calavera @dave-tucker

**Comment by dave-tucker** [comment]
LGTM. I know nothing about systemd though ;)
If there is a particular pattern that a plugin author should use with their unit files to make use of socket activation it would be worth making a note of it in the docs here.

**Comment by runcom** [comment]
@dave-tucker totally agree wrt the need of docs about this feature - I'm writing a blog post about this and I've planned to extend the official Docker docs to mention this :)

**Comment by dave-tucker** [comment]
@runcom :star2: !

**Comment by calavera** [comment]
Sorry, I'm late to reviewing this, but why is this enabled by default without even checking if the host is using systemd? I'm aware that major distros are adopting it, making it the default without checking does NOT LGTM.

**Comment by runcom** [comment]
@calavera I have another PR opened - I'll add the check there

**Comment by calavera** [comment]
@runcom please, do.

**Pull request merged**
