### PR TITLE
Add volume List/Get calls

### PR DESCRIPTION
**Pull request by cpuguy83**
Also adds tests for the volume API

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @calavera

**Comment by runcom** [comment]
Ci is broken :(

**Comment by cpuguy83** [comment]
yeah, what the heck is that.

**Comment by calavera** [comment]
you might want to re-push to force a new shiny build.

**Comment by cpuguy83** [comment]
wtf is up with the ci here...

**Comment by vdemeester** [comment]
ping @calavera @runcom @cpuguy83  how are we on that ? This would be really cool to have it merged :angel: 

Travis-ci is green, and circleci should be disabled I think.

**Comment by runcom** [comment]
This LGTM

**Comment by calavera** [comment]
I've disabled CircleCI in this repo.

Change LGTM.

**Comment by vdemeester** [comment]
@calavera :tada:

**Pull request merged**
