### PR TITLE
Update MAINTAINERS file

### PR DESCRIPTION
**Pull request by thaJeztah**
the script in docker/opensource didn't like the format (but we can consider changing the format a bit in future) :-)

### CODE REVIEW

**Comment by runcom** [comment]
@thaJeztah can I have my email changed to runcom@redhat.com? I don't use that email anymore :angel:

**Comment by thaJeztah** [comment]
@runcom sure, updated :+1:

**Comment by runcom** [comment]
Thanks! :heart: gonna update it in docker/docker asap

LGTM

**Comment by thaJeztah** [comment]
@runcom there you go: https://github.com/docker/docker/pull/19142

**Comment by runcom** [comment]
@thaJeztah so much love :heart: :heart: :heart: :heart:

**Comment by thaJeztah** [comment]
haha, easy fix :)

**Comment by calavera** [comment]
LGTM

**Pull request merged**
